### ISSUE TITLE
Newer build

### ISSUE THREAD

**Issue by tannertechnology** [QuiCM/EssentialsPlus#19]
Newer build generated at https://github.com/dkstanner/EssentialsPlus/releases/tag/1.2

Created via Github Actions

https://github.com/QuiCM/EssentialsPlus/pull/18

**Comment by dkstanner** [comment]
@QuiCM If you create a new release it should run the action and attach the dll to that existing release, check out my repo for more info. It confused me for sure which is why I ended up deleting and re-forking the repo. 

As soon as a new release is published (I think the version should be bumped to 1.2) I'm happy to close off this issue. I'm doing some local work on fixes for the permissions issues. /back also isn't working for /myhome but works for /home. If there is TShock documentation that helps with this like there was with the /back fixes it would be immensely helpful.

Thanks for your work on TShock and this, I understand it is a lot and appreciate the opportunity to contribute.

**Comment by QuiCM** [comment]
Done done :)
